export enum ActionConstent {
    SET_ZIPCODES = 'SET_ZIPCODES',
    ADD_ZIPCODE = 'ADD_ZIPCODE',
    SET_ZIPCODESDISTANCE = 'SET_ZIPCODESDISTANCE',
    REMOVE_ZIPCODES = 'REMOVE_ZIPCODES',
    REMOVE_ZIPCODESDISTANCE = 'REMOVE_ZIPCODESDISTANCE'
}